http://localhost:3001
Content-Type: application/json
POST /api/persons
{
    "name": "Ada Lovelace",
    "number": "123456789",
}
# {
#     'name': 'Dan Abramov',
#     'number': '12-43-234345',
# }
# {
#     'name': 'Mary Poppendieck',
#     'number': '39-23-6423122',
# }
# {
#     'name': 'Jacob Biehler',
#     'number': '8584845307',
# }
# {
#     'name': 'henlo',
#     'number': '0987654321',
# }
# {
#     'name': 'hello',
#     'number': '1234567890',
# }
# {
#     'name': 'wowee',
#     'number': '159753456',
# }
# {
#     'name': 'ejwpajfio',
#     'number': '1919189',
# }
